/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_test_demos_demos_jni_JNiTest */

#ifndef _Included_com_test_demos_demos_jni_JNiTest
#define _Included_com_test_demos_demos_jni_JNiTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_test_demos_demos_jni_JNiTest
 * Method:    getStringFromNDK
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_test_demos_demos_jni_JNiTest_getStringFromNDK
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
