/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "../../../../../../Library/Android/sdk/ndk-bundle/sysroot/usr/include/jni.h"
/* Header for class com_test_demos_demos_jni_NewJniTest */

#ifndef _Included_com_test_demos_demos_jni_NewJniTest
#define _Included_com_test_demos_demos_jni_NewJniTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_test_demos_demos_jni_NewJniTest
 * Method:    getNewTxt
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_test_demos_demos_jni_NewJniTest_getNewTxt
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
